---
title: "DAGs"
format: html
editor: visual
---

```{r}
#| include: false
#| screenshot: true
library(here)
library(DiagrammeR)
library(tidyverse)
library(dplyr)
```

Overall relationship between Exposure (X) and Outcome (Y):

```{r echo=FALSE}
#| echo: false
grViz("
digraph {
  graph [label='A: exposure, Y: outcome\n
  U: set of all confounders\n
  θ′₁: total effect of A on Y',
  labelloc='b', fontsize=8]
  
  node [shape = plaintext]
    A [label = 'A']
    Y [label = 'Y']
    U [label = 'U']
  edge [minlen = 1.5]
    A->Y [label = 'θ′₁']
    U->A [label = '']
    U->Y [label = '']
  { rank = same; A; Y }
  { rank = max; U;}
}")
```

Relationship between Exposure (X) and Outcome (Y) through mediator (M):

```{r echo=FALSE}
#| echo: false

grViz("
digraph {
  graph [label='A: exposure, Y: outcome\n
  M: mediator, U: set of all confounders\n
  β₁: effect of A on M\n
  θ₂: effect of M on Y\n
  θ₁: direct effect of A on Y\n
  β₁.θ₂: indirect effect of A on Y\n
  θ′₁: total effect of A on Y (= β₁.θ₂ + θ₁)',
  labelloc='b', fontsize=8]
  
  node [shape = plaintext]
    A [label = 'A']
    M [label = 'M']
    Y [label = 'Y']
    U [label = 'U']
  edge [minlen = 1.5]
    A->Y [xlabel = 'θ′₁', label = 'θ₁']
    A->M [xlabel = 'β₁']
    M->Y [label = 'θ₂']
    U->A [label = '']
    U->Y [label = '']
  { rank = same; A; Y }
  { rank = min; M;}
  { rank = max; U;}
}")
```

Example: How much does body mass index explain the relation between physical activity and pulse rate?

```{r echo=FALSE}
#| echo: false
grViz("
digraph {
  graph []
  node [shape = plaintext]
    A [label = 'Physical activity']
    M [label = 'BMI']
    Y [label = 'Pulse']
  edge [minlen = 1.5]
    A->Y [label = 'θ₁', xlabel = 'θ′₁']
    A->M [xlabel = 'β₁']
    M->Y [label = 'θ₂']
  { rank = same; A; Y }
  { rank = min; M;}
}")
```

```{r}
#| echo: false

grViz("
digraph {
  graph []
  node [shape = plaintext]
    C [label = 'C']
    A [label = 'A']
    M [label = 'M']
    Y [label = 'Y']
  edge [minlen = 2]
    A->M
    M->Y
    A->Y
    C->A
    C->Y
    C->M
{rank = same; C; A; M; Y; }
}
")
```

A: Exposure; Y: Outcome; M: Mediator; C: confounding factors on the pathways
